language: cpp

jobs:
  include:

  - os: linux
    dist: trusty
    compiler: gcc
    env:
      - COMPILER=g++-9.2
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']

cache:
  directories:
    - docker_images

before_install:
  -  |
    image=`sha1sum quisp/Dockerfile`
    docker load -i docker_images/${image}.tar || true

after_install:
  -  |
    image=`sha1sum quisp/Dockerfile`
    docker save -o docker_images/$(image).tar `docker images quisp -q`
  
services:
  - docker
install: travis_wait sh docker_build.sh
script: 
  - sh docker_run_lint.sh 
  - sh docker_run_test.sh 
  - cd test && sudo python -m unittest discover && sudo rm testresults.txt && echo "test done"
branches:
  only:
    - master
    - Unittest
