language: cpp

jobs:
  include:

  - os: linux
    dist: trusty
    compiler: gcc
    env:
      - COMPILER=g++-9.2
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']

services:
  - docker

before_install:
- sh docker_build.sh
- sh ./test/test_docker_run.sh

script: quisp exec google test
branches:
  only:
    - master
    - Unittest