# This is not unittest, only build and result test
# language is python because using python unittest to check result
# simulator itself is c++
language: python

services:
  - docker

before_install:
- sh docker_build.sh

script: sh test_docker_run.sh && cd test && python -m unittest discover && rm testresults.txt && echo "test done"
branches:
  only:
    - master
    - Unittest