language: cpp

jobs:
  include:

  - os: linux
    dist: trusty
    compiler: gcc
    env:
      - COMPILER=g++-9.2
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
env:
  global:
    - OMNETPP_VERSION=5.6.1
    - PATH=/home/travis/build/sfc-aqua/quisp/omnetpp/bin:$PATH
before_install:
 - sudo apt-get -y update
 - sudo apt-get install -y qt5-default libqt5opengl5-dev libgtk-3-0 libwebkitgtk-3.0-0 default-jre osgearth libeigen3-dev cmake source
 - echo "Building Omnetpp"
 - sudo wget https://github.com/omnetpp/omnetpp/releases/download/omnetpp-${OMNETPP_VERSION}/omnetpp-${OMNETPP_VERSION}-src-linux.tgz --referer=https://omnetpp.org/ -O omnetpp-src-linux.tgz --progress=dot:giga
 - tar xf omnetpp-src-linux.tgz
 - sudo rm omnetpp-src-linux.tgz
 - sudo mkdir omnetpp
 - sudo mv omnetpp-${OMNETPP_VERSION}/* omnetpp
 - cd omnetpp
 - sudo source setenv
 - sudo ./configure WITH_OSG=no WITH_QTENV=no
 - make -j $(nproc) MODE=release base
 - sudo rm -r doc out test samples misc config.log config.status
 - echo "Build Omnet success"
 - echo "Building Googletest" 
 - sudo wget https://github.com/google/googletest/archive/release-1.10.0.tar.gz
 - sudo tar xf release-1.10.0.tar.gz
 - cd googletest-release-1.10.0
 - mkdir build
 - cd build
 - sudo cmake -DBUILD_SHARED_LIBS=0 ..
 - sudo make
 - sudo cp -a include/gtest /usr/include
 - sudo cp -a libgtest_main.so libgtest.so /usr/lib/
 - which valgrind
 - cd "${TRAVIS_BUILD_DIR}"
script: sh ./test/test.sh
branches:
  only:
    - master
    - Unittest