[omnetpp-wasm-build]

# preloaded files
ned-folders = [
	"./networks",
	"./channels",
	"./modules"
]
images = [
	"./images"
]
ini-file = "./networks/omnetpp.ini"
project-folder = "./quisp"
output-folder = "./wasm-out"
