name: quisp main
on: [push, pull_request]
jobs:
  all:
    runs-on: ubuntu-latest
    container:
      image: omnetpp/omnetpp:u18.04-5.6.2
    steps:
      - name: Install the latest git and dependencies
        run: |
          apt-get update -y
          apt-get install -y --no-install-recommends software-properties-common cmake g++ clang-format clang-tidy
          add-apt-repository ppa:git-core/ppa
          apt-get update -y
          apt-get install git -y
      - name: Check out repository
        uses: actions/checkout@v2
      - name: clang-format and clang-tidy
        run: make ci
      - name: unit tests
        run: |
          opp_makemake -f --deep -O out -i ./makefrag -M release --make-so
          make run-unit-test
        working-directory: quisp
      # - name: module tests
        # run: make run-module-test
      - name: Run Simulations
        run: /bin/bash test.sh
        working-directory: test
      - name: Check Simulation Results
        run: python -m unittest discover
        working-directory: test

